### ISSUE TITLE
Faltam imagens no protótipo

### ISSUE THREAD

**Issue by oliveirosnt** [LucasCBrasil/MeuCarro#1]
Primeiro, tá muito massa, porém acredito que pra ficar melhor de visualizar como você realmente pretende deixar a página inicial do sistema, acredito que a colocação de imagens (mesmo que provisórias) iriam ajudar a ver melhor.

**Comment by LucasCBrasil** [comment]
Com certeza, realmente ajudariam melhor a compreender o design pensado para a aplicação. Obrigado pelo feedback!
