### ISSUE TITLE
Adição de mais detalhes

### ISSUE THREAD

**Issue by jpedrotc1** [LucasCBrasil/MeuCarro#2]
Projeto bacana, mas poderia também incluir um espaço para que fossem adicionados mais detalhes sobre o veículo. Como emplacamento e etc.

**Comment by LucasCBrasil** [comment]
Massa, com certeza tem informações importantes com relação aos veiculos que podem ser colocadas como maiores detalhes aos usuários, obrigado pela sugestão!
