### ISSUE TITLE
Separar a implementação das funcionalidades do arquivo de rotas.

### ISSUE THREAD

**Issue by joseiscj** [LucasCBrasil/MeuCarro#3]
Sugiro dividir o código de funcionalidades em controllers, pois as mesmas estão nos arquivos de routes. Fazer a separação do código de funcionalidades dos arquivos de routes é uma boa prática na codificação.

**Comment by LucasCBrasil** [comment]
Com certeza, essa é uma boa ideia mesmo para as funcionalidades, obrigado pela dica!
