### ISSUE TITLE
Sugestões de melhoria

### ISSUE THREAD

**Issue by mateusqc** [LucasCBrasil/MeuCarro#5]
Grande Lucas! Tudo em paz? Tenho algumas sugestões de mudanças para você.

-  Utilizar o App.js apenas para redirecionamento de URLs com o React Router;
-  Encapsular a listagem de carros em um componente que internamente possui sua lógica e chama o componente Carro, o que seria o requisito da entrega 5;
-  Organizar a árvore de diretórios de forma a separar as páginas do seu sistema dos componentes criados para propósitos específicos, por exemplo:
    -  Diretório components armazenando apenas componentes isolados, cada um em sua pasta específica e com um arquivo `index.js` (arquivos css também, caso necessário) contendo o seu respectivo código principal a ser importado;
    -  Diretório pages dentro do src contendo todas as páginas do sistema e importando os componentes da pasta components conforme necessário.

É isso, cara. Bom desenvolvimento e simbora dar o gás!

**Comment by LucasCBrasil** [comment]
Grande Mateus, obrigado pelas sugestões. De fato já estou analisando para usar o React Router(ainda não consegui pelo pouco tempo dedicado ao projeto kkk), mas será utilizado sim. Valeu pela dica de um componente para a listagem, realmente vai ser muito bom fazer isso, inclusive para essa entrega da semana 5 como você falou. Também, quando tiver mais dedicado ao projeto, realizare essa melhor organização dos diretórios. Muito obrigado pelas dicas, abraço.
